### ISSUE TITLE
Add more bootcamps to the existing list in the README

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-bootcamps#10]
We already have a few bootcamps listed but there are many more out there that are not in the current list. If you seen a bootcamp that should be included on the list, then please read through the [CONTRIBUTING.md](https://github.com/thisdot/tech-bootcamps/blob/main/CONTRIBUTING.md) file first before making a pull request. 

**Please note: this issue will remain open and not assigned to anyone. We encourage multiple contributors to add their bootcamps to the list.**

Make sure to include a description for each bootcamp you add.

**Comment by ludovicobesana** [comment]
@jdwilkin4 Thank you!
I'm adding some bootcamps
