### ISSUE TITLE
Add descriptions to the existing list of bootcamps in the README

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-bootcamps#11]
We already have a few bootcamps listed in the README but none of them include descriptions. It would be nice if people knew what courses these bootcamps teach. 

Please include a short 1-2 sentence description for each bootcamp on the list. 

Here is an example:
```md
## Tech Bootcamps

- [100Devs](https://leonnoel.com/100devs/)
  This is a free 30 week software engineering bootcamp that you can take online. You will learn full stack JavaScript and learn about how to land your first developer job.
  <br>
```
**Please note: If you are interested in working on this, leave a comment on this issue and we will assign it to you.**

**Comment by YashPimple** [comment]
@jdwilkin4 can you assign it to me would like to work on it?

**Comment by jdwilkin4** [comment]
It has been assigned to you 👍

**Comment by jdwilkin4** [comment]
@YashPimple 

Also, if you were interested in having this PR count towards hacktoberfest, it has to be merged during the month of October. Any PR's approved and merged before October 1st won't count towards hacktoberfest. 

We have a few people interested in making contributions to our repos and had questions about this, so I just wanted to mention it here too 👍
